Repository brainbox-ai/brainbox-backend, pull requests merged in 2023-05, with the labels that each got.

#1 config .env
  .gitignore
  brainbox_api/brainbox/api/serializers.py
  brainbox_api/brainbox/api/urls.py
  brainbox_api/brainbox/api/views.py
  brainbox_api/brainbox/apps.py
  brainbox_api/brainbox/migrations/0001_initial.py
  brainbox_api/brainbox/migrations/0002_remove_message_creator.py
  brainbox_api/brainbox/models.py
  brainbox_api/brainbox_api/settings.py
  brainbox_api/brainbox_api/urls.py
Labels: bug

#4 Restructuring folder names
  brainbox_api/api/__init__.py
  brainbox_api/api/admin.py
  brainbox_api/api/apps.py
  brainbox_api/api/migrations/0001_initial.py
  brainbox_api/api/migrations/0002_remove_message_creator.py
  brainbox_api/api/migrations/__init__.py
  brainbox_api/api/models.py
  brainbox_api/api/serializers.py
  brainbox_api/api/tests.py
  brainbox_api/api/urls.py
  brainbox_api/api/views.py
  brainbox_api/brainbox/views.py
  brainbox_api/brainbox_api/settings.py
  brainbox_api/brainbox_api/urls.py
Labels: configuration

#5 add django cors headers
  brainbox_api/brainbox_api/settings.py
  requirements.txt
Labels: configuration

#6 chat memory functionality
  brainbox_api/api/views.py
Labels: enhancement

#7 Configure postgresql
  brainbox_api/brainbox_api/settings.py
  requirements.txt
Labels: configuration

#9 Debate test
  brainbox_api/api/urls.py
  brainbox_api/api/views.py
Labels: enhancement

#10 build multiple profiles and debates
  brainbox_api/api/debates.py
  brainbox_api/api/migrations/0003_profile_debate.py
  brainbox_api/api/models.py
  brainbox_api/api/serializers.py
  brainbox_api/api/urls.py
  brainbox_api/api/views.py
Labels: enhancement, configuration

#11 fix typos in debates.py and increase CharField limit for Debates
  brainbox_api/api/debates.py
  brainbox_api/api/models.py
Labels: bug
